[tool.poetry]
name = "secsep"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "3.10.12"
colorama = "^0.4.6"
click = "^8.2.1"
pandas = "^2.3.1"
pyparsing = "^3.2.3"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
